export const PROPERTY_SCOPE_VERSION = '1.2.0';
export const PROPERTY_SCOPE_BUILD_ID = 'PS-P1.2-EVIDENCE-WORKSPACE-20260721';
export const PROPERTY_SCOPE_BUILD_LABEL = `NFE PropertyScope Phase ${PROPERTY_SCOPE_VERSION} — ${PROPERTY_SCOPE_BUILD_ID}`;
